### ISSUE TITLE
Custom build

### ISSUE THREAD

**Issue by CodeOfTheProgrammer** [icons8/line-awesome#26]
Are there any plans to support creating custom builds containing only the icons I use in my app? Currently line-awesome.min.css takes up about half of my bundle.css file even though I'm only using 7 of the icons in my app. It would be especially useful for improving load times for mobile users.

**Comment by fatawesome** [comment]
Hello @CodeOfTheProgrammer! Right now we are not planning to implement tree shaking for the font. But here are few things which might be useful for you:
1. You can consider using svg assets instead of the actual font (available in /src dir)
2. You can perform font optimization and delete glyphs which you don't use. There are a lot of tools available for this purpose.
I honestly think that first variant is much better for you.

**Comment by CodeOfTheProgrammer** [comment]
I'll use the svg assets. Thanks.
