### ISSUE TITLE
.fa class not working after upgrade

### ISSUE THREAD

**Issue by kyonkopa** [icons8/line-awesome#33]
After upgrading to v1.3.0 I couldn't get **fa fa-** css to work i.e. icons don't unless you use **la la-**, I've tried using font-awesome-line-awesome/css/all.css stylesheet but it still doesn't work, is this the expected behavior?

**Comment by fatawesome** [comment]
As far as we know, there is no more `fa-` prefix in FontAwesome. It was replaced by style prefixes.

**Comment by kyonkopa** [comment]
Yes, but I mean fas far doesn't show line awesome icons anymore, unless las lar, it won't work. However it worked in the previous versions.

**Comment by fatawesome** [comment]
Are you sure you did everything correct? This snippet works for me.
```
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- Font Awesome -->
    <script src="https://kit.fontawesome.com/b238dc89ed.js" crossorigin="anonymous"></script>

    <!-- Font Awesome to Line Awesome CDN link -->
    <link rel="stylesheet" href="https://maxst.icons8.com/vue-static/landings/line-awesome/font-awesome-line-awesome/css/all.min.css">
    
    <title>FA->LA test</title>
</head>
<body>
    <i class="fas fa-heart"></i>
</body>
</html>
```

**Comment by kyonkopa** [comment]
I've tested your code and it works. I'm using the downloadable version and it doesn't have `font-awesome-line-awesome/css/all.min.css` file, what it does have is `css/line-awesome.css`. I also have installed it via npm which has `all.min.css` but it still **doesn't** show line awesome icons, what it does show are the font awesome icons. However using that from the cdn works fine

**Comment by fatawesome** [comment]
Thanks for your answer! We will add FA -> LA files to the package soon.

**Comment by kyonkopa** [comment]
That´s great. Thanks

**Comment by kyonkopa** [comment]
@fatawesome Any update on this? Last time I checked it hasn't been added

**Comment by NicoHood** [comment]
I am still wondering where to get the mentioned css file or how to recompile it myself.

**Comment by kyonkopa** [comment]
If you really need it to work, try this.

1. Import "font-awesome-line-awesome/css/all.min.css", pull from CDN if necessary, also available in npm package
2. Place "fa-" prefixed fonts in css/webfonts, you can get these files from the line-awesome npm package

**Comment by NicoHood** [comment]
Alright, so I tried to dig into this issue once again.

To correctly use line-awesome as font-awesome 4 AND 5 drop-in you need to:
* Download Line Awesome 1.3.0 from the website
* Rename all files in /fonts from `la-` to `fa-`
* Download the compatibility file from ``

However this is very confusing because you must rename the files and the compatibility css is hosted an an URL you must know. Also I have no idea how to recreate the css file from source myself. I was able to get it running using the new `fas` syntax, but not using the old v4 `fa` syntax.

Maybe it would be nice, if you can provide a shim file, like font awesome:
```
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/all.css">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.1/css/v4-shims.css">
```

It would be nice, if you could clarify this, how to compile those css files yourself, maybe even without renaming the font files (as it is missleading).

**Comment by NicoHood** [comment]
So I tried to recompile the scss from the download myself. It required a fix in order to use `fas` instead of `las`. I wanted to open a PR for that, but it seems the git here has no up to date versions!? Can you please upload all files here?

https://github.com/icons8/line-awesome/tree/master/dist/line-awesome/scss

The fix was to add to `_core.scss`
```scss
.#{$la-css-prefix-lar},
.#{$la-css-prefix-las},
.#{$la-css-prefix-lab} {
  -moz-osx-font-smoothing: grayscale;
  -webkit-font-smoothing: antialiased;
  display: inline-block;
  font-style: normal;
  font-variant: normal;
  text-rendering: auto;
  line-height: 1;
}
```

Include variables first:
```scss
@import "mixins";
@import "variables";
@import "core";
@import "path";
@import "larger";
@import "fixed-width";
@import "list";
@import "bordered_pulled";
@import "rotated-flipped";
@import "stacked";
@import "icons";
@import "screen-reader";
```

And replace the following variables:
```scss
$la-css-prefix: fa;

$la-font-name-lar: 'Font Awesome 5 Pro' !default;
$la-css-prefix-lar: far !default;

$la-font-name-las: 'Font Awesome 5 Free' !default;
$la-css-prefix-las: fas !default;

$la-font-name-lab: 'Font Awesome 5 Brands' !default;
$la-css-prefix-lab: fab !default;
```

==>  old v4 `fa` Syntax is still not working. Even with `la` it is not working and I have no idea how you generated the css file linked in my previous post

**Comment by NicoHood** [comment]
I've upgraded my grav quark theme and published those changes to github. You can test with the following html. Note: I have not added line-awesome "v4" legacy support, only for Fontawesome 4, 5, and LineAwesome 1.3.0. So all `la` icons will not functions, but `las, fas, fa` will work.
```
v4fa <i class="fa fa-heart"></i>
v5fas <i class="fas fa-heart"></i>
v4la <i class="la la-heart"></i>
v5las <i class="las la-heart"></i>

v4fa <i class="fa fa-amazon"></i>
v5fas <i class="fab fa-amazon"></i>
v4la <i class="la la-amazon"></i>
v5las <i class="lab la-amazon"></i>

v4fa <i class="fa fa-star-o"></i>
v5far <i class="far fa-star"></i>
v5fas <i class="fas fa-star"></i>
v4la <i class="la la-star-o"></i>
v5lar <i class="lar la-star"></i>
v5fas <i class="las la-star"></i>
```

It is possible that the scss needs to be recompiled using `npm i && npm run build` (I did not yet add css files to the repo).
https://github.com/NicoHood/grav-theme-quark/tree/magerquark
