### ISSUE TITLE
Where can i find Line-Awesome v 1.1

### ISSUE THREAD

**Issue by armin-gitter** [icons8/line-awesome#43]
Hi I want to download line-awesome version 1.1
please give me the download link, thanks.

**Comment by fatawesome** [comment]
This one?
https://maxst.icons8.com/vue-static/landings/line-awesome/line-awesome/1.1.0/css/line-awesome.min.css

**Comment by ajselvig** [comment]
This is just the css, is there any way to access the landing page for that time (like this: https://web.archive.org/web/20190115173233/https://icons8.com/line-awesome)? We have a legacy project using this version but it's difficult choosing icons since there are considerable differences with the current version.
