### ISSUE TITLE
css pseudo-elements not working

### ISSUE THREAD

**Issue by pjadanowski** [icons8/line-awesome#49]
Hi,
i'm trying to set line-awesome icon in pseudo element in css but i isn't working
my class is:
```
.breadcrumb-content .list-items li:before {   
    position: absolute;  
    content: "\f105";  
    font-family: "Line Awesome Free";  
}  
```
right angle does not appear

**Comment by fatawesome** [comment]
Because icons have their dedicated prefixes. For the right angle it is .las (as you may noticed on https://icons8.com/line-awesome).
To use icons in the way you showed (without having a prefix) you need to add styles which are usually added by prefix.
In your case its `font-weight: 900`

Please tell me if it helped you.

**Comment by fatawesome** [comment]
Well, hopefully you are ok there :)
Feel free to reopen the issue if you still have problems.

**Comment by pjadanowski** [comment]
thanks, it works ;)
